# Generated by Django 5.2.8 on 2025-12-04 18:42

import nuam_usuario.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuam_usuario', '0003_rename_archivo_pdf_certificado_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='archivo',
            field=models.FileField(upload_to='certificados/', validators=[nuam_usuario.validators.validar_extension_archivo]),
        ),
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to='documentos/', validators=[nuam_usuario.validators.validar_extension_archivo]),
        ),
    ]
