# Generated by Django 5.2.8 on 2025-12-04 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuam_usuario', '0004_alter_certificado_archivo_alter_documento_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='usuario',
        ),
        migrations.AddField(
            model_name='certificado',
            name='calificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados', to='nuam_usuario.calificacion'),
        ),
    ]
